const state={map:null,status:null,mapCanvas:null,tool:'view',dragStart:null,dragPoint:null,panStart:null,teleopTimer:null,draft:[],view:{scale:1,offsetX:0,offsetY:0,initialized:false}};
const canvas=document.querySelector('#map'),context=canvas.getContext('2d'),message=document.querySelector('#message');
const tips={view:'查看模式：左键拖动平移，滚轮缩放；点击“适配全图”复位',initial:'初始位姿：在地图上按住并拖拽，确定机器人位置与朝向',goal:'2D Goal Pose：在地图上按住并拖拽，发布目标位置与朝向',navigation:'Navigation Goal：在地图上按住并拖拽，直接请求 Nav2 导航动作',waypoint:'添加航点：在地图上按住并拖拽，确定航点位置与机器人到点后的朝向'};
async function api(path,body=null){const response=await fetch(path,body===null?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(response.status===401){window.location.assign('/login');throw new Error('登录已失效')}if(!response.ok)throw new Error(data.error||'请求失败');return data}
function show(text,error=false){message.textContent=text;message.classList.toggle('error',error)}
function selectedMap(){return document.querySelector('#nav-map-select').value}
function selectedRoute(){return document.querySelector('#route-select').value||document.querySelector('#route-name').value.trim()}
function setTool(tool){state.tool=tool;document.querySelectorAll('[data-tool]').forEach(button=>button.classList.toggle('active',button.dataset.tool===tool));document.querySelector('#map-tip').textContent=tips[tool];canvas.style.cursor=tool==='view'?'grab':'crosshair'}
function statusText(status){const wp=status.waypoint||{};document.querySelector('#mode-chip').textContent=status.mode==='idle'?'待命':status.mode==='mapping'?'建图中':'导航中';document.querySelector('#pose').textContent=status.pose?`${status.pose_source} · ${status.pose.x}, ${status.pose.y}`:'等待位姿';document.querySelector('#teleop-status').textContent=status.teleop_enabled?(status.mode==='navigation'?'导航时锁定':'可用'):'已禁用';document.querySelector('#teleop').classList.toggle('disabled',!status.teleop_enabled||status.mode==='navigation');document.querySelector('#waypoint-status').textContent=wp.state||'离线';document.querySelector('#waypoint-progress').textContent=wp.current_waypoint?`${wp.current_waypoint}/${wp.waypoint_count}`:(wp.waypoint_count?`0/${wp.waypoint_count}`:'—');document.querySelector('#connection').textContent='Orin 已连接';document.querySelector('#connection').className='badge online';if(status.last_error)show(status.last_error,true)}
function resizeCanvas(){const rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1,width=Math.max(1,Math.round(rect.width*ratio)),height=Math.max(1,Math.round(rect.height*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;if(state.map&&!state.view.initialized)fitView();draw()}}
function fitView(){if(!state.map)return;const padding=32*(window.devicePixelRatio||1),scale=Math.min((canvas.width-padding*2)/state.map.width,(canvas.height-padding*2)/state.map.height);state.view.scale=Math.max(.03,scale);state.view.offsetX=(canvas.width-state.map.width*state.view.scale)/2;state.view.offsetY=(canvas.height-state.map.height*state.view.scale)/2;state.view.initialized=true;draw()}
function buildMapImage(map){const image=context.createImageData(map.width,map.height);for(let y=0;y<map.height;y++)for(let x=0;x<map.width;x++){const value=map.data[(map.height-1-y)*map.width+x],i=(y*map.width+x)*4,gray=value<0?88:Math.max(0,255-Math.round(value*2.55));image.data[i]=gray;image.data[i+1]=gray;image.data[i+2]=gray;image.data[i+3]=255}const layer=document.createElement('canvas');layer.width=map.width;layer.height=map.height;layer.getContext('2d').putImageData(image,0,0);state.mapCanvas=layer;if(!state.view.initialized)fitView()}
function drawArrow(x,y,yaw,color){const size=13/state.view.scale;context.save();context.translate(x,y);context.rotate(-yaw);context.fillStyle=color;context.beginPath();context.moveTo(size,0);context.lineTo(-size*.72,size*.58);context.lineTo(-size*.72,-size*.58);context.closePath();context.fill();context.restore()}
function routePixel(point){return{x:(point.x-state.map.origin.x)/state.map.resolution,y:state.map.height-(point.y-state.map.origin.y)/state.map.resolution}}
function drawRoute(){if(!state.draft.length)return;context.save();context.strokeStyle='#fbbf24';context.lineWidth=2/state.view.scale;context.beginPath();state.draft.forEach((point,index)=>{const p=routePixel(point);if(index)context.lineTo(p.x,p.y);else context.moveTo(p.x,p.y)});context.stroke();state.draft.forEach((point,index)=>{const p=routePixel(point);drawArrow(p.x,p.y,point.yaw,'#fbbf24');context.save();context.fillStyle='#111827';context.strokeStyle='#fde68a';context.lineWidth=1/state.view.scale;context.beginPath();context.arc(p.x,p.y,12/state.view.scale,0,Math.PI*2);context.fill();context.stroke();context.fillStyle='#fff';context.font=`${12/state.view.scale}px sans-serif`;context.textAlign='center';context.textBaseline='middle';context.fillText(String(index+1),p.x,p.y);context.restore()});context.restore()}
function draw(){const empty=document.querySelector('#map-empty');context.setTransform(1,0,0,1,0,0);context.fillStyle='#060c16';context.fillRect(0,0,canvas.width,canvas.height);if(!state.map||!state.mapCanvas){empty.classList.remove('hidden');return}empty.classList.add('hidden');context.save();context.translate(state.view.offsetX,state.view.offsetY);context.scale(state.view.scale,state.view.scale);context.drawImage(state.mapCanvas,0,0);const pose=state.status?.pose;if(pose)drawArrow((pose.x-state.map.origin.x)/state.map.resolution,state.map.height-(pose.y-state.map.origin.y)/state.map.resolution,pose.yaw,'#f43f5e');drawRoute();if(state.dragStart&&state.dragPoint){context.strokeStyle=state.tool==='waypoint'?'#fbbf24':'#38bdf8';context.lineWidth=2/state.view.scale;context.beginPath();context.moveTo(state.dragStart.x,state.dragStart.y);context.lineTo(state.dragPoint.x,state.dragPoint.y);context.stroke();drawArrow(state.dragStart.x,state.dragStart.y,Math.atan2(-(state.dragPoint.y-state.dragStart.y),state.dragPoint.x-state.dragStart.x),state.tool==='waypoint'?'#fbbf24':'#38bdf8')}context.restore()}
function screenPoint(event){const rect=canvas.getBoundingClientRect(),ratio=canvas.width/rect.width;return{x:(event.clientX-rect.left)*ratio,y:(event.clientY-rect.top)*ratio}}
function mapPoint(screen){return{x:(screen.x-state.view.offsetX)/state.view.scale,y:(screen.y-state.view.offsetY)/state.view.scale}}
function worldPoint(pixel,end){return{x:state.map.origin.x+pixel.x*state.map.resolution,y:state.map.origin.y+(state.map.height-pixel.y)*state.map.resolution,yaw:Math.atan2(-(end.y-pixel.y),end.x-pixel.x)}}
async function refreshStatus(){try{state.status=await api('/api/status');statusText(state.status);draw()}catch(error){document.querySelector('#connection').textContent='连接断开';document.querySelector('#connection').className='badge offline';if(error.message!=='登录已失效')show(error.message,true)}}
async function refreshMap(){try{const map=await api('/api/map');if(map.available&&(!state.map||map.stamp.sec!==state.map.stamp.sec||map.stamp.nanosec!==state.map.stamp.nanosec)){const dimensionChanged=!state.map||map.width!==state.map.width||map.height!==state.map.height;state.map=map;if(dimensionChanged)state.view.initialized=false;buildMapImage(map);draw()}}catch(_){}}
async function refreshMaps(){try{const result=await api('/api/maps'),select=document.querySelector('#nav-map-select'),previous=select.value;select.innerHTML='';if(!result.maps.length)select.add(new Option('暂无保存地图',''));result.maps.forEach(map=>select.add(new Option(map.name,map.name)));if([...select.options].some(option=>option.value===previous))select.value=previous;await refreshRoutes()}catch(error){show(error.message,true)}}
async function refreshRoutes(){const mapName=selectedMap(),select=document.querySelector('#route-select'),previous=select.value;select.innerHTML='';if(!mapName){select.add(new Option('请先选择地图',''));return}try{const result=await api(`/api/routes?map_name=${encodeURIComponent(mapName)}`);if(!result.routes.length)select.add(new Option('暂无保存路线',''));result.routes.forEach(route=>select.add(new Option(`${route.name} · ${route.waypoint_count} 点`,route.name)));if([...select.options].some(option=>option.value===previous))select.value=previous}catch(error){show(error.message,true)}}
async function loadRoute(){const mapName=selectedMap(),routeName=selectedRoute();if(!mapName||!routeName)throw new Error('请先选择地图和路线');const route=await api(`/api/route?map_name=${encodeURIComponent(mapName)}&route_name=${encodeURIComponent(routeName)}`);state.draft=route.waypoints;document.querySelector('#route-name').value=route.route_name||routeName;draw();await api('/api/waypoint/command',{action:'load',map_name:mapName,route_name:routeName});show(`已载入 ${state.draft.length} 个航点`)}
async function saveRoute(){const mapName=selectedMap(),routeName=document.querySelector('#route-name').value.trim();if(!mapName)throw new Error('请先选择已保存地图');if(!routeName)throw new Error('请输入路线名称');const result=await api('/api/routes/save',{map_name:mapName,route_name:routeName,waypoints:state.draft});await refreshRoutes();document.querySelector('#route-select').value=routeName;await api('/api/waypoint/command',{action:'load',map_name:mapName,route_name:routeName});show(result.message)}
async function deleteRoute(){const mapName=selectedMap(),routeName=selectedRoute();if(!mapName||!routeName)throw new Error('请选择需要删除的路线');const result=await api('/api/routes/delete',{map_name:mapName,route_name:routeName});state.draft=[];draw();await refreshRoutes();show(result.message)}
async function patrol(action){const body={action};if(action==='start'){body.map_name=selectedMap();body.route_name=selectedRoute();if(!body.map_name||!body.route_name)throw new Error('请先选择地图和已保存路线')}const result=await api('/api/waypoint/command',body);show(result.message)}
function bindPost(id,path,body,after){document.querySelector(id).onclick=async()=>{try{const result=await api(path,body());show(result.message);if(after)await after();refreshStatus()}catch(error){show(error.message,true)}}}
bindPost('#start-mapping','/api/mapping/start',()=>({}));bindPost('#stop-system','/api/system/stop',()=>({}));bindPost('#save-map','/api/map/save',()=>({map_name:document.querySelector('#save-name').value}),refreshMaps);bindPost('#start-navigation','/api/navigation/start',()=>({map_name:selectedMap()}));document.querySelector('#refresh-maps').onclick=refreshMaps;document.querySelector('#refresh-routes').onclick=refreshRoutes;document.querySelector('#nav-map-select').onchange=refreshRoutes;document.querySelector('#route-select').onchange=()=>{document.querySelector('#route-name').value=document.querySelector('#route-select').value};document.querySelector('#load-route').onclick=()=>loadRoute().catch(error=>show(error.message,true));document.querySelector('#save-route').onclick=()=>saveRoute().catch(error=>show(error.message,true));document.querySelector('#delete-route').onclick=()=>deleteRoute().catch(error=>show(error.message,true));document.querySelector('#clear-route').onclick=()=>{state.draft=[];draw();show('已清空当前未保存航点')};document.querySelector('#start-patrol').onclick=()=>patrol('start').catch(error=>show(error.message,true));document.querySelector('#pause-patrol').onclick=()=>patrol('pause').catch(error=>show(error.message,true));document.querySelector('#resume-patrol').onclick=()=>patrol('resume').catch(error=>show(error.message,true));document.querySelector('#stop-patrol').onclick=()=>patrol('stop').catch(error=>show(error.message,true));document.querySelector('#fit-map').onclick=fitView;document.querySelectorAll('[data-tool]').forEach(button=>button.onclick=()=>setTool(button.dataset.tool));
canvas.addEventListener('pointerdown',event=>{if(!state.map)return;canvas.setPointerCapture(event.pointerId);const point=screenPoint(event);if(state.tool==='view'){state.panStart={x:point.x,y:point.y,offsetX:state.view.offsetX,offsetY:state.view.offsetY};return}state.dragStart=mapPoint(point);state.dragPoint=state.dragStart;draw()});canvas.addEventListener('pointermove',event=>{const point=screenPoint(event);if(state.panStart){state.view.offsetX=state.panStart.offsetX+point.x-state.panStart.x;state.view.offsetY=state.panStart.offsetY+point.y-state.panStart.y;draw();return}if(state.dragStart){state.dragPoint=mapPoint(point);draw()}});canvas.addEventListener('pointerup',async event=>{if(state.panStart){state.panStart=null;return}if(!state.dragStart)return;const start=state.dragStart,end=mapPoint(screenPoint(event));state.dragStart=null;state.dragPoint=null;draw();const point=worldPoint(start,end);if(state.tool==='waypoint'){state.draft.push({name:`航点 ${state.draft.length+1}`,...point});draw();show(`已添加航点 ${state.draft.length}；请保存路线`);return}const endpoint=state.tool==='initial'?'/api/initialpose':state.tool==='goal'?'/api/goal':'/api/navigation_goal';try{const result=await api(endpoint,point);show(result.message)}catch(error){show(error.message,true)}});canvas.addEventListener('wheel',event=>{if(!state.map)return;event.preventDefault();const screen=screenPoint(event),before=mapPoint(screen),factor=event.deltaY<0?1.14:1/1.14,newScale=Math.min(20,Math.max(.025,state.view.scale*factor));state.view.scale=newScale;state.view.offsetX=screen.x-before.x*newScale;state.view.offsetY=screen.y-before.y*newScale;state.view.initialized=true;draw()},{passive:false});canvas.addEventListener('contextmenu',event=>event.preventDefault());new ResizeObserver(resizeCanvas).observe(canvas);
function sendTeleop(linear,angular){return api('/api/teleop',{linear,angular}).catch(error=>show(error.message,true))}function stopTeleop(){if(state.teleopTimer)clearInterval(state.teleopTimer);state.teleopTimer=null;sendTeleop(0,0)}function beginTeleop(linear,angular){if(state.teleopTimer)clearInterval(state.teleopTimer);sendTeleop(linear,angular);state.teleopTimer=setInterval(()=>sendTeleop(linear,angular),150)}document.querySelectorAll('.teleop-key').forEach(button=>{const linear=Number(button.dataset.linear),angular=Number(button.dataset.angular);button.addEventListener('pointerdown',()=>beginTeleop(linear,angular));['pointerup','pointerleave','pointercancel'].forEach(name=>button.addEventListener(name,stopTeleop))});window.addEventListener('keydown',event=>{if(event.target.matches('input,select'))return;const keys={w:[.20,0],a:[0,.70],s:[-.20,0],d:[0,-.70]},motion=keys[event.key.toLowerCase()];if(motion&&!event.repeat){event.preventDefault();beginTeleop(...motion)}});window.addEventListener('keyup',event=>{if(['w','a','s','d'].includes(event.key.toLowerCase()))stopTeleop()});window.addEventListener('blur',stopTeleop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTeleop()});document.querySelector('#logout').onclick=async()=>{stopTeleop();await fetch('/api/auth/logout',{method:'POST'});window.location.assign('/login')};setTool('view');resizeCanvas();refreshStatus();refreshMap();refreshMaps();setInterval(refreshStatus,1000);setInterval(refreshMap,1500);
